rules:
  anonymous-definition:
    # https://docs.zizmor.sh/audits/#anonymous-definition
    disable: true
  concurrency-limits:
    # https://docs.zizmor.sh/audits/#concurrency-limits
    disable: true
  secrets-outside-env:
    # https://docs.zizmor.sh/audits/#secrets-outside-env
    disable: true
  superfluous-actions:
    # https://docs.zizmor.sh/audits/#superfluous-actions
    disable: true
  undocumented-permissions:
    # https://docs.zizmor.sh/audits/#undocumented-permissions
    disable: true
