ARG DEBIAN_CODENAME
FROM rust:slim-$DEBIAN_CODENAME
COPY ./docker/build-scripts/vars.* /build-scripts/
COPY ./docker/build-scripts/buildenv.sh /build-scripts/
ARG TARGETPLATFORM
ENV DEBIAN_FRONTEND=noninteractive
RUN sh /build-scripts/buildenv.sh linux/amd64 $TARGETPLATFORM
RUN mkdir -p /build
WORKDIR /build
