#!/bin/sh -eu

PROGNAME="$(basename $0)"
BASEDIR="$(cd $(dirname $0); pwd)"
PROJDIR="$(cd $BASEDIR/..; pwd)"
CURRENT=$(git describe --abbrev=0)

NO_COMMIT=NO

help() {
    cat <<EOF >&2
USAGE:
  $PROGNAME [--no-commit] (major|minor|patch)
  $PROGNAME -h | --help

OPTIONS:
  -h, --help

ARGUMENTS:
  major
    Update the major version.

  minor
    Update the minor version.

  patch
    Update the patch version.
EOF
    exit 0
}

log() {
  echo "$1" >&2
}

error() {
  log "ERROR: $1"
  exit 1
}

while [ $# -gt 0 ]
do
  case "$1" in
    '-h' | '--help')
      help
      ;;
    '--no-commit')
      NO_COMMIT=YES
      shift
      ;;
    'major' | 'minor' | 'patch')
      break
      ;;
    *)
      help
      ;;
  esac
done

VERSION=$(npx semver $CURRENT -i $1)

log "Pulling changes from origin..."
git pull

log "Bumping the version to $VERSION..."
for MANIFEST in $(find $PROJDIR -name Cargo.toml)
do
  # Don't use the -i option of `sed`.
  # The incompatibility between macOS and GNU will cause troubles.
  sed -e "s/^version = .*/version = \"$VERSION\"/" $MANIFEST | sponge $MANIFEST
done
cargo build
git add .
if [ "$NO_COMMIT" = NO ]; then
  git commit -m "misc: bump version to $VERSION"
fi

# TODO: Genereate CHANGELOG.md

if [ "$NO_COMMIT" = NO ]; then
  log "Making an annotated tag for $VERSION..."
  git tag -a "$VERSION" -m "release: $VERSION"
fi

cat <<EOF >&2
Done.

Run the following commands after confirmation:

  git push -u origin main
  git push origin $VERSION
EOF
