#!/usr/bin/env node

const fs = require('fs');
const { Transform, pipeline } = require('stream');

class Replay extends Transform {
  constructor(options) {
    super(options)
    this.stream = fs.createReadStream(options.file);
  }

  _transform(data, encoding, callback) {
    // Replace TS packets with ones read from the file.
    callback(null, this.stream.read(data.length));
  }
}

pipeline(
  process.stdin,
  new Replay({ file: process.argv[2] }),
  process.stdout,
  (err) => {});
