#!/bin/sh -eu

PROJDIR=$(cd $(dirname $0)/..; pwd)
TARGET_FILE=resources/mirakurun.openapi.json

if [ "$(pwd)" != "$PROJDIR" ]
then
  echo "ERROR: must run in the project root"
  exit 1
fi

# Format with jq so that we can see changes easily.
$PROJDIR/scripts/mirakurun-openapi-json -c | $PROJDIR/scripts/fixup-openapi-json | \
  jq >$TARGET_FILE

if git diff --quiet -- $TARGET_FILE
then
  echo "Not changed"
else
  git add $TARGET_FILE
  git commit -m "build: update $TARGET_FILE"
fi
