#!/bin/sh -eu

PROJDIR=$(cd $(dirname $0)/..; pwd)
TARGET_FILE=docker/build-scripts/mirakc-arib.sh

if [ "$(pwd)" != "$PROJDIR" ]
then
  echo "ERROR: must run in the project root"
  exit 1
fi

CURRENT=$(grep 'MIRAKC_ARIB_VERSION=' $TARGET_FILE | cut -d '=' -f 2 | tr -d '"')

URL='https://api.github.com/repos/mirakc/mirakc-arib/tags'
VERSION="$(curl -fsSL $URL | jq -r '.[0].name')"

TEMP_FILE=$(mktemp)
trap "rm -f $TEMP_FILE" EXIT INT TERM

# Don't use the -i option of `sed`.
# The incompatibility between macOS and GNU will cause troubles.
sed -r -e "s|^MIRAKC_ARIB_VERSION=.*|MIRAKC_ARIB_VERSION=\"$VERSION\"|" $TARGET_FILE >$TEMP_FILE
mv -f $TEMP_FILE $TARGET_FILE

if git diff --quiet -- $TARGET_FILE
then
  echo "Not changed"
else
  git add $TARGET_FILE
  git commit -m "build(deps): bump mirakc-arib from $CURRENT to $VERSION"
  $PROJDIR/scripts/update-tools-images --push
fi
