#!/bin/sh

set -eu

PROGNAME=$(basename $0)
BASEDIR=$(cd $(dirname $0); pwd)
PROJDIR=$(cd $BASEDIR/..; pwd)

REGS='docker.io ghcr.io'
IMAGE=mirakc/tools
DISTROS='alpine debian'

if [ "$(uname)" != Linux ] || id -nG | grep -q docker; then
  DOCKER='docker'
else
  DOCKER='sudo docker'
fi

PUSH_OPT=
VERSION=

help() {
  cat <<EOF >&2
Update $IMAGE images.

USAGE:
  $PROGNAME [<version>]
  $PROGNAME -h | --help

OPTIONS:
  -h, --help
    Show help.

  --push
    Push images.

ARGUMENTS:
  <version>
    Optional version number.

DESCRIPTION:
  This script build $IMAGE images and optionally push them to Docker Hub and
  GHCR.

  You have to login to the registries by \`docker login\` before running this
  script with \`--push\`.
EOF
  exit 0
}

log() {
  echo "$1" >&2
}

error() {
  log "ERROR: $1"
  exit 1
}

platforms() {
  case $1 in
    alpine)
      echo 'linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64/v8'
      ;;
    debian)
      echo 'linux/386,linux/amd64,linux/arm/v7,linux/arm64/v8'
      ;;
  esac
}

# Use a base image other than `scratch` in order to make it possible to run
# commands with `docker run mirakc/tools:<tag> <command>`.
base_image() {
  case $1 in
    alpine)
      echo 'busybox'
      ;;
    debian)
      echo 'debian:buster-slim'
      ;;
  esac
}

while [ $# -gt 0 ]
do
  case "$1" in
    '-h' | '--help')
      help
      ;;
    '--push')
      PUSH_OPT='--push'
      shift
      ;;
    *)
      break
      ;;
  esac
done

if [ $# -gt 0 ]
then
  VERSION="$1"
fi

for DISTRO in $DISTROS
do
  PLATFORMS=$(platforms $DISTRO)
  BASE_IMAGE=$(base_image $DISTRO)
  IMG="$IMAGE:$DISTRO"
  if [ -n "$VERSION" ]
  then
    IMG="$IMG-$VERSION"
  fi
  for REG in $REGS
  do
    log "Updating $REG/$IMG..."
    docker buildx build \
      -t $REG/$IMG \
      -f $PROJDIR/docker/Dockerfile.tools \
      --platform="$PLATFORMS" \
      --build-arg="DISTRO=$DISTRO" \
      --build-arg="BASE_IMAGE=$BASE_IMAGE" \
      $PUSH_OPT $PROJDIR
  done
done
