name: Pull Request

on:
  pull_request:
    branches:
      - master

jobs:
  linux-build:
  macos-build:
  arm-linux-build:
  coverage:
    needs:
      - linux-build
      - macos-build
      - arm-linux-build
  auto-merge:
    if: github.actor == 'dependabot[bot]'
    needs:
      - linux-build
      - macos-build
      - arm-linux-build
      - coverage
