name: build

on:
  workflow_call:

permissions: {}

jobs:
  build:
    strategy:
      matrix:
        runner:
          - macos-latest
          - ubuntu-latest
        rust:
          - stable
          #- nightly
    runs-on: ${{ matrix.runner }}
    continue-on-error: ${{ matrix.runner == 'macos-latest' }}  # macOS is unsupported officially
    permissions:
      contents: read
    steps:
      - name: mirakc-arib is required for tests
        run: |
          ln -sf $(which true) /usr/local/bin/mirakc-arib
          test $(which mirakc-arib) = /usr/local/bin/mirakc-arib
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - name: Install gtimeout and macfuse (macos)
        if: matrix.runner == 'macos-latest'
        run: |
          brew install coreutils macfuse
      - uses: dtolnay/rust-toolchain@e97e2d8cc328f1b50210efc529dca0028893a2d9 # v1
        with:
          toolchain: ${{ matrix.rust }}
          components: 'clippy, rustfmt'
      - uses: Swatinem/rust-cache@779680da715d629ac1d338a641029a2f4372abb5 # v2.8.2
      - uses: taiki-e/install-action@385db9cc6bf65d19775b02084a4b698eaca9a4f2 # v2.68.19
        with:
          tool: cargo-deny nextest zizmor
      - name: Check
        run: make check
      - name: Build
        run: |
          cargo build -v --release
      - name: Run tests
        run: |
          cargo nextest run --release --all-features
        env:
          RUST_LOG: debug
      - name: Tests for OpenAPI document
        run: |
          # TODO(ci): enable recording/timeshift features
          cat <<EOF >config.yml
          resource:
            strings-yaml: resources/strings.yml
          EOF
          cargo run -r --bin=mirakc -- -c config.yml openapi openapi.json
          # openapi-generator-cli
          npx @openapitools/openapi-generator-cli generate -i openapi.json \
            -g rust -o mirakc-client --package-name mirakc-client
          # TODO: add more tests if needed
