name: update

on:
  workflow_call:
    inputs:
      ref-name:
        required: true
        type: string
    secrets:
      CI_BOT_APP_ID:
        required: true
      CI_BOT_PRIVATE_KEY:
        required: true
      DOCKERHUB_TOKEN:
        required: true
      DOCKERHUB_USER:
        required: true
    outputs:
      num-commits:
        description: >-
          The number of commits made within 24 hours.
        value: ${{ jobs.update.outputs.num-commits }}

permissions: {}

env:
  DEBIAN_CODENAME: trixie

jobs:
  update:
    runs-on: ubuntu-latest
    outputs:
      num-commits: ${{ steps.count.outputs.num-commits }}
    # Use the default GitHub bot account because we don't need to invoke any
    # other workflows triggered by a push event.
    permissions:
      contents: write
    steps:
      - uses: actions/create-github-app-token@29824e69f54612133e76f7eaac726eef6c875baf # v2.2.1
        id: app-token
        with:
          app-id: ${{ secrets.CI_BOT_APP_ID }}
          private-key: ${{ secrets.CI_BOT_PRIVATE_KEY }}
          # The access will be scoped to only the current repository.
          permission-contents: write
      - name: Get GitHub App User ID
        id: get-user-id
        run: |
          USER_ID=$(gh api "/users/${APP_SLUG}[bot]" --jq .id)
          echo "user-id=$USER_ID" >>"$GITHUB_OUTPUT"
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
          APP_SLUG: ${{ steps.app-token.outputs.app-slug }}
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
          token: ${{ steps.app-token.outputs.token }}
          ref: ${{ inputs.ref-name }}
      # See https://github.com/actions/create-github-app-token?tab=readme-ov-file#configure-git-cli-for-an-apps-bot-user
      - name: git config
        run: |
          git config --global user.name "$USER_NAME"
          git config --global user.email "$USER_EMAIL"
        env:
          USER_NAME: ${{ steps.app-token.outputs.app-slug }}[bot]
          USER_EMAIL: ${{ steps.get-user-id.outputs.user-id }}+${{ steps.app-token.outputs.app-slug }}[bot]@users.noreply.github.com
      # See https://github.com/tschaub/gh-pages/issues/384#issuecomment-1236047843
      - name: set origin url (workaround)
        run: |
          git remote set-url origin "https://x-access-token:${TOKEN}@github.com/${GITHUB_REPOSITORY}"
        env:
          TOKEN: ${{ steps.app-token.outputs.token }}
      - name: Setup QEMU user-mode emulation
        uses: docker/setup-qemu-action@ce360397dd3f832beb865e1373c09c0e9f86d70a # v4.0.0
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f # v3.12.0
        with:
          buildkitd-flags: --debug
      - name: Login to Docker Hub
        uses: docker/login-action@b45d80f862d83dbcd57f89517bcf500b2ab88fb2 # v4.0.0
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@b45d80f862d83dbcd57f89517bcf500b2ab88fb2 # v4.0.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Update .devcontainer/Dockerfile
        run: |
          if [ -e ./scripts/update-devcontainer-dockerfile.sh ]
          then
            sh ./scripts/update-devcontainer-dockerfile.sh
          else
            ./scripts/update-devcontainer-dockerfile
          fi
      - name: Update mirakc-arib
        if: inputs.ref-name == 'main'
        run: |
          LAST_COMMIT=$(git rev-parse HEAD)
          if [ -e ./scripts/update-mirakc-arib.sh ]
          then
            sh ./scripts/update-mirakc-arib.sh
          else
            ./scripts/update-mirakc-arib
          fi
          if [ "$(git rev-parse HEAD)" != "$LAST_COMMIT" ]
          then
            if [ -e ./scripts/update-tools-images.sh ]
            then
              sh ./scripts/update-tools-images.sh --no-cache --push "$DEBIAN_CODENAME"
            else
              ./scripts/update-tools-images --no-cache --push "$DEBIAN_CODENAME"
            fi
          fi
        env:
          # GH_TOKEN is used by `gh api` command in update-mirakc-arib.sh.
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Push if changed
        run: |
          if git diff --quiet origin/${REF_NAME}..HEAD
          then
            echo "No commit to push"
          else
            git push
          fi
        env:
          REF_NAME: ${{ inputs.ref-name }}
      - name: Count commits made within 24 hours
        id: count
        run: |
          NUM_COMMITS=$(git rev-list --count --since '24 hours' "$REF_NAME")
          echo "NUM_COMMITS=$NUM_COMMITS"
          echo "num-commits=$NUM_COMMITS" >>$GITHUB_OUTPUT
        env:
          REF_NAME: ${{ inputs.ref-name }}
