name: weekly

on:
  schedule:
    - cron: '19 19 * * 5'  # every Friday
  workflow_dispatch:

permissions: {}

env:
  DENO_DIR: /tmp/deno

jobs:
  release:
    runs-on: ubuntu-latest
    # Use the `mirakc-ci` bot account in order to invoke the release workflow
    # triggered by a push event for a release tag.
    permissions:
      contents: write
    steps:
      - uses: actions/create-github-app-token@29824e69f54612133e76f7eaac726eef6c875baf # v2.2.1
        id: app-token
        with:
          app-id: ${{ secrets.CI_BOT_APP_ID }}
          private-key: ${{ secrets.CI_BOT_PRIVATE_KEY }}
          # The access will be scoped to only the current repository.
          permission-contents: write
      - name: Get GitHub App User ID
        id: get-user-id
        run: |
          USER_ID=$(gh api "/users/${APP_SLUG}[bot]" --jq .id)
          echo "user-id=$USER_ID" >>"$GITHUB_OUTPUT"
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
          APP_SLUG: ${{ steps.app-token.outputs.app-slug }}
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
          token: ${{ steps.app-token.outputs.token }}
          # Always checkout the release branch.
          ref: release
          # Fetch all history for all tags and branches so that `git describe`
          # works properly.
          fetch-depth: 0
      - uses: dtolnay/rust-toolchain@e97e2d8cc328f1b50210efc529dca0028893a2d9 # v1
        with:
          toolchain: stable
      - uses: denoland/setup-deno@e95548e56dfa95d4e1a28d6f422fafe75c4c26fb # v2.0.3
        with:
          deno-version: v2.x
      # See https://github.com/actions/create-github-app-token?tab=readme-ov-file#configure-git-cli-for-an-apps-bot-user
      - name: git config
        run: |
          git config --global user.name "$USER_NAME"
          git config --global user.email "$USER_EMAIL"
        env:
          USER_NAME: ${{ steps.app-token.outputs.app-slug }}[bot]
          USER_EMAIL: ${{ steps.get-user-id.outputs.user-id }}+${{ steps.app-token.outputs.app-slug }}[bot]@users.noreply.github.com
      # See https://github.com/tschaub/gh-pages/issues/384#issuecomment-1236047843
      - name: set origin url (workaround)
        run: |
          git remote set-url origin "https://x-access-token:${TOKEN}@github.com/${GITHUB_REPOSITORY}"
        env:
          TOKEN: ${{ steps.app-token.outputs.token }}
      - run: |
          TAG="$(git describe --tags --abbrev=0)"
          if git diff --quiet "$TAG"
          then
            echo "Not changed, skip to create new release"
          else
            if [ -e ./scripts/release.sh ]
            then
              sh ./scripts/release.sh patch
            else
              ./scripts/release patch
            fi
            git push
            git push --tags
          fi
